[package]
name = "zfs-replicate"
version = "2.0.0"
authors = ["Alex Brandt <alunduil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
