blank_issues_enabled: true
contact_links:
  - name: Questions / support
    url: https://github.com/alunduil/zfs-replicate#getting-support
    about: For usage questions and support, see the getting-support section of the README.
