name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
          - "3.9"  # EOL 2025-10
          - "3.10"  # EOL 2026-10
          - "3.11"  # EOL 2027-10
          - "3.12"  # EOL 2028-10
        experimental: [false]
        include:
          - python-version: 3.x
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: poetry install
        run: poetry install
      - name: poetry run pytest
        run: poetry run pytest
      - name: poetry run coveralls
        if: matrix.python-version == '3.x'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run pytest
          poetry run coveralls --service=github || poetry run coveralls --service=github-actions

  scripts:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
          - "3.9"  # EOL 2025-10
          - "3.10"  # EOL 2026-10
          - "3.11"  # EOL 2027-10
          - "3.12"  # EOL 2028-10
        experimental: [false]
        include:
          - python-version: 3.x
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: poetry install
        run: poetry install
      - name: zfs-replicate --help
        run: poetry run -- zfs-replicate --help

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.12"
      - name: poetry build
        run: |
          poetry build
          tar -zvtf dist/zfs_replicate-*.tar.gz | grep zfs/replicate/
          tar -zvtf dist/zfs_replicate-*.tar.gz | grep zfs_test/replicate_test/
      - name: poetry check
        run: poetry check

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v2
