# This workflow runs poetry against the repository.
#
# You can adjust the behavior by modifying this file.
name: Publish to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: setup python
        uses: actions/setup-python@v4
        with:
          cache: poetry
      - name: poetry build
        run: poetry build
      - name: poetry publish
        run: poetry publish  --username __token__ --password=${{ secrets.PYPI_API_TOKEN }}
